### ISSUE TITLE
New Heads To Add

### ISSUE THREAD

**Issue by Ki-Seki** [IAAR-Shanghai/Awesome-Attention-Heads#2]
* https://aclanthology.org/2021.eacl-srw.2.pdf
* https://openreview.net/pdf?id=rJgoYekkgB
* https://www.prophy.science/search/experimental/?q=cta-122380~cta-116368
* https://arxiv.org/abs/2407.02646

**Comment by fan2goa1** [comment]
I will add this four papers ASAP.

**Comment by fan2goa1** [comment]
I have already added the first two papers into README.md, as the last one don't define a new Head.
